### ISSUE TITLE
    - langchain=0.0.350

### ISSUE THREAD

**Issue by kuivi** [koldunovn/climsight#38]
In the environment.yml, the version of langchain is explicitly defined as 0.0.350. In my case, it did not find ChatOpenAI (at from langchain.chat_models import ChatOpenAI), however, updating to version 0.1.14 resolved the issue. 
Is the any reason for the 0.1.14 /?

**Comment by AntoniaJost** [comment]
This was introduced by commit 98dc6d46982e9172548768d62fc562560fc4520c by @koldunovn. Maybe he can  let us know what were the thoughts behind it.

**Comment by koldunovn** [comment]
It wasn't working at the time with latest OpenAi package. Please check the installation without it and iif it works, do PR to change it!
